name: AI Code Comment Review Extension

on: [workflow_dispatch]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug container contents
        run: |
          ls -la 
          tree

      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-comment-review-agent@main # Stable tested 1.0.3
        with:
          config-path: "ai-comment-review.yaml"
          score-threshold: 85
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
