name: AI Code Review Extension
on: [push, pull_request]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug container contents
        run: |
          ls -la 
          tree
          
      - name: Run AI Code Review Agent
        # uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.0.3 # Stable tested 1.0.3
        uses: Manav-Khandurie/agents/code-review-agent@main # unstable
        with:
          config-path: "./ai-review.yaml"
          score-threshold: 75
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
