name: AI Code Review Extension
on: [push, pull_request]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.0.3 # Stable tested 1.0.3
        with:
          config-path: "./ai-review.yaml"
          score-threshold: 85
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}