name: AI Code Review Extension
on: [push, pull_request]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.1.0 # Stable tested 1.1.0
        # uses: Manav-Khandurie/agents/code-review-agent@main # unstable
        with:
          config-path: "./ai-review.yaml"
          score-threshold: 75
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_API_BASE_GEMMA3: ${{ secrets.HF_API_BASE_GEMMA3 }}
