name: ISSUE AGENT

on: [workflow_dispatch]

jobs:
  comment-review:
    runs-on: ubuntu-latest
    outputs:
      review-report: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3

      - name: Run AI Code Comment Review Agent
        uses: Manav-Khandurie/agents/code-comment-review-agent@code-comment-review-agent-v1.0.0
        with:
          config-path: "./ai-comment-review.yaml"
          score-threshold: 75
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

      - name: Upload AI comment review result
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: code-comment-review-report
          path: code_comment_review_result.json

  ai-review:
    runs-on: ubuntu-latest
    needs: comment-review
    steps:
      - uses: actions/checkout@v3

      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.1.0
        with:
          config-path: "./ai-review.yaml"
          score-threshold: 75
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

      - name: Upload AI review result
        uses: actions/upload-artifact@v4
        with:
          name: code-review-report
          path: code_review_result.json

  issue-agent:
    name: Issue agents
    runs-on: ubuntu-latest
    needs: [comment-review, ai-review]
    steps:
      - uses: actions/checkout@v3
        with:
          path: codebase
      - name: Create /data directory
        run: mkdir -p data

      - name: Download comment review artifact
        uses: actions/download-artifact@v4
        with:
          name: code-comment-review-report
          path: data/

      - name: Download code review artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: code-review-report
          path: data/
      
      - name: Run Issue Agent
        uses: Manav-Khandurie/agents/issue-agent@issue-agent-v2.0.0
        with:
          src: "./data"
          provider: "openai"
          model_name: "gpt-4o-mini"
          api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.TOKEN_GITHUB }}
          github_repo: ${{ github.repository }}